[build]
  base = "apps/website"
  publish = "."
  command = "echo skip"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]


