[build]
  base = "apps/website"
  publish = "."
  command = "echo skip"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#static"
  targetPort = 5001
  port = 8888


